"""Add Messages class

Revision ID: 002f79476473
Revises: eb8077ff6ef4
Create Date: 2023-08-04 12:41:16.662813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002f79476473'
down_revision = 'eb8077ff6ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.String(length=500), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['substitutes.id'], name=op.f('fk_messages_recipient_id_substitutes')),
    sa.ForeignKeyConstraint(['sender_id'], ['teachers.id'], name=op.f('fk_messages_sender_id_teachers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
