"""Removed Message Class

Revision ID: 07b9bf933474
Revises: 002f79476473
Create Date: 2023-08-04 12:48:55.965126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b9bf933474'
down_revision = '002f79476473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), nullable=True),
    sa.Column('message_content', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['substitutes.id'], name='fk_messages_recipient_id_substitutes'),
    sa.ForeignKeyConstraint(['sender_id'], ['teachers.id'], name='fk_messages_sender_id_teachers'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
