"""added confirmationEnum & updated Request Class

Revision ID: 0d2bd2b44415
Revises: 07b9bf933474
Create Date: 2023-08-04 13:12:05.337936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2bd2b44415'
down_revision = '07b9bf933474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('Message_sub_sent_to',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Teacher_if_declined',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_requests_Message_sub_sent_to_substitutes'), 'substitutes', ['Message_sub_sent_to'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_requests_Teacher_if_declined_teachers'), 'teachers', ['Teacher_if_declined'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_requests_Teacher_if_declined_teachers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_requests_Message_sub_sent_to_substitutes'), type_='foreignkey')
        batch_op.alter_column('Teacher_if_declined',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('Message_sub_sent_to',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
