"""removed Request

Revision ID: 13074fa51901
Revises: a7015b0f2d71
Create Date: 2023-07-27 10:55:27.887889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13074fa51901'
down_revision = 'a7015b0f2d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.Column('substitute_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_requests_course_id_courses'),
    sa.ForeignKeyConstraint(['substitute_id'], ['users.id'], name='fk_requests_substitute_id_users'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name='fk_requests_teacher_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
