"""added Request class

Revision ID: 19932d998adb
Revises: 21e4ce1bdaf4
Create Date: 2023-07-27 10:11:30.834987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19932d998adb'
down_revision = '21e4ce1bdaf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('substitute_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Requested', 'Confirmed', 'Declined'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_requests_course_id_courses')),
    sa.ForeignKeyConstraint(['substitute_id'], ['users.id'], name=op.f('fk_requests_substitute_id_users')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_requests_teacher_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
