"""empty message

Revision ID: 1f180dfb2c79
Revises: b18f5d993690
Create Date: 2023-07-28 11:41:46.574760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f180dfb2c79'
down_revision = 'b18f5d993690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_teachers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_teachers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('school_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('location', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_teachers_user_id_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_teachers_email'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
