"""added write_id to review- testing seed again

Revision ID: 1fb0d3aba2e9
Revises: dd36593086df
Create Date: 2023-07-28 10:47:58.076506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb0d3aba2e9'
down_revision = 'dd36593086df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_writer_id_users'), 'users', ['writer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_writer_id_users'), type_='foreignkey')
        batch_op.drop_column('writer_id')

    # ### end Alembic commands ###
