"""added course_id and updated relationships in class Request

Revision ID: 371cde8acf7f
Revises: e8d5d83e8cfd
Create Date: 2023-08-08 19:54:13.900684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371cde8acf7f'
down_revision = 'e8d5d83e8cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_requests_course_id_courses'), 'courses', ['course_id'], ['Course_ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_requests_course_id_courses'), type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
