"""Add many-to-many relationship

Revision ID: 412e4cfa3a5a
Revises: e7f6c0c5c83d
Create Date: 2023-07-26 09:55:17.865506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412e4cfa3a5a'
down_revision = 'e7f6c0c5c83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_substitute_association',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('substitute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['substitute_id'], ['substitutes.id'], name=op.f('fk_teacher_substitute_association_substitute_id_substitutes')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_teacher_substitute_association_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('teacher_id', 'substitute_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_substitute_association')
    # ### end Alembic commands ###
