"""Create tables

Revision ID: 7d2f6b068abc
Revises: 
Create Date: 2023-08-11 19:43:46.985035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2f6b068abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('profile_picture', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('substitute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('qualifications', sa.String(length=200), nullable=True),
    sa.Column('verification_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_substitute_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('school_name', sa.String(length=100), nullable=False),
    sa.Column('school_location', sa.String(length=100), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_teacher_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substitute_user_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('course_being_covered', sa.String(length=100), nullable=False),
    sa.Column('confirmation', sa.Boolean(), nullable=True),
    sa.Column('message_sub_sent_to', sa.String(length=120), nullable=True),
    sa.Column('teacher_if_declined', sa.Boolean(), nullable=True),
    sa.Column('school_name', sa.String(length=100), nullable=False),
    sa.Column('teacher_school_location', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['substitute_user_id'], ['substitute.id'], name=op.f('fk_request_substitute_user_id_substitute')),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['teacher.id'], name=op.f('fk_request_teacher_user_id_teacher')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_teacher_id', sa.Integer(), nullable=False),
    sa.Column('substitute_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_teacher_id'], ['teacher.id'], name=op.f('fk_review_reviewer_teacher_id_teacher')),
    sa.ForeignKeyConstraint(['substitute_id'], ['substitute.id'], name=op.f('fk_review_substitute_id_substitute')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('request')
    op.drop_table('teacher')
    op.drop_table('substitute')
    op.drop_table('user')
    # ### end Alembic commands ###
