"""updated Review Class

Revision ID: a7015b0f2d71
Revises: 19932d998adb
Create Date: 2023-07-27 10:27:47.060249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7015b0f2d71'
down_revision = '19932d998adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_substitute_reviewed_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_teacher_reviewed_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_substitute_reviewed_id_substitutes'), 'substitutes', ['substitute_reviewed_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_teacher_reviewed_id_teachers'), 'teachers', ['teacher_reviewed_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_teacher_reviewed_id_teachers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_substitute_reviewed_id_substitutes'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_teacher_reviewed_id_users', 'users', ['teacher_reviewed_id'], ['id'])
        batch_op.create_foreign_key('fk_reviews_substitute_reviewed_id_users', 'users', ['substitute_reviewed_id'], ['id'])

    # ### end Alembic commands ###
