"""Create tables

Revision ID: b139f3a2da6a
Revises: 
Create Date: 2023-08-07 20:54:30.839750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b139f3a2da6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('Teacher', 'Substitute', 'SiteAdmin'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('school_name', sa.String(length=120), nullable=True),
    sa.Column('school_location', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('site_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_site_admins_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('substitutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('qualifications', sa.String(length=120), nullable=True),
    sa.Column('verification_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_substitutes_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('course_name', sa.String(length=120), nullable=True),
    sa.Column('school_name', sa.String(length=120), nullable=True),
    sa.Column('school_location', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_teachers_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('courses',
    sa.Column('Course_ID', sa.Integer(), nullable=False),
    sa.Column('Course_name', sa.String(length=120), nullable=True),
    sa.Column('Correlating_teacher_ID', sa.Integer(), nullable=True),
    sa.Column('Correlating_substitute_ID', sa.Integer(), nullable=True),
    sa.Column('Course_status', sa.Enum('Available', 'Unavailable'), nullable=True),
    sa.Column('Course_school_name', sa.String(length=120), nullable=True),
    sa.Column('Course_location', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['Correlating_substitute_ID'], ['substitutes.id'], name=op.f('fk_courses_Correlating_substitute_ID_substitutes')),
    sa.ForeignKeyConstraint(['Correlating_teacher_ID'], ['teachers.id'], name=op.f('fk_courses_Correlating_teacher_ID_teachers')),
    sa.PrimaryKeyConstraint('Course_ID')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Substitute_user_id', sa.Integer(), nullable=False),
    sa.Column('Teacher_id', sa.Integer(), nullable=False),
    sa.Column('Course_Being_covered', sa.String(length=120), nullable=True),
    sa.Column('Confirmation', sa.String(length=10), nullable=True),
    sa.Column('Message_sub_sent_to', sa.String(length=120), nullable=True),
    sa.Column('Teacher_if_declined', sa.String(length=120), nullable=True),
    sa.Column('school_name', sa.String(length=120), nullable=True),
    sa.Column('Teacher_school_location', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['Substitute_user_id'], ['substitutes.id'], name=op.f('fk_requests_Substitute_user_id_substitutes')),
    sa.ForeignKeyConstraint(['Teacher_id'], ['teachers.id'], name=op.f('fk_requests_Teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('Review_ID', sa.Integer(), nullable=False),
    sa.Column('Teacher_Id', sa.Integer(), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=True),
    sa.Column('Review', sa.String(length=255), nullable=True),
    sa.Column('Correlating_Substitute_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Correlating_Substitute_ID'], ['substitutes.id'], name=op.f('fk_reviews_Correlating_Substitute_ID_substitutes')),
    sa.ForeignKeyConstraint(['Teacher_Id'], ['teachers.id'], name=op.f('fk_reviews_Teacher_Id_teachers')),
    sa.PrimaryKeyConstraint('Review_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('requests')
    op.drop_table('courses')
    op.drop_table('teachers')
    op.drop_table('substitutes')
    op.drop_table('site_admins')
    op.drop_table('users')
    # ### end Alembic commands ###
