"""Add teacher-substitute association and indexes

Revision ID: b58f24f83de0
Revises: 412e4cfa3a5a
Create Date: 2023-07-26 10:02:11.687215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58f24f83de0'
down_revision = '412e4cfa3a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitutes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_substitutes_grade_or_course'), ['grade_or_course'], unique=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_grade_or_course'), ['grade_or_course'], unique=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_teachers_grade_or_course'))

    with op.batch_alter_table('substitutes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_substitutes_grade_or_course'))

    # ### end Alembic commands ###
