"""Add Request column

Revision ID: bf4b08860aa6
Revises: bed415060476
Create Date: 2023-07-29 17:56:07.556504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4b08860aa6'
down_revision = 'bed415060476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_requests_Teacher_id_teachers'), 'teachers', ['Teacher_id'], ['id'])
        batch_op.drop_column('Teacher_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Teacher_name', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_requests_Teacher_id_teachers'), type_='foreignkey')
        batch_op.drop_column('Teacher_id')

    # ### end Alembic commands ###
