"""Update models

Revision ID: eb8077ff6ef4
Revises: d5d66e9bb513
Create Date: 2023-08-04 10:11:11.426620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8077ff6ef4'
down_revision = 'd5d66e9bb513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('Substitute_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('Teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('Teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Substitute_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
